# Generated by Django 6.0.1 on 2026-02-27 02:17

import datetime
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomblockschedule',
            options={'ordering': ['room', 'day_of_week', 'date_start'], 'verbose_name': 'Room Block Schedule', 'verbose_name_plural': 'Room Block Schedules'},
        ),
        migrations.AlterModelOptions(
            name='roombooking',
            options={'ordering': ['-date_start'], 'verbose_name': 'Room Booking', 'verbose_name_plural': 'Room Bookings'},
        ),
        migrations.RemoveIndex(
            model_name='roombooking',
            name='rooms_roomb_booking_6456ae_idx',
        ),
        migrations.RenameField(
            model_name='roomblockschedule',
            old_name='end_date',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='roomblockschedule',
            old_name='start_date',
            new_name='date_start',
        ),
        migrations.RemoveField(
            model_name='roomblockschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='roomblockschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='roomblockschedule',
            name='block_type',
            field=models.CharField(choices=[('routine', 'Blok Rutin'), ('maintenance', 'Maintenance'), ('event', 'Kegiatan'), ('other', 'Lainnya')], default='routine', max_length=20),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='date_end',
            field=models.DateField(default=datetime.date(2026, 2, 27), verbose_name='Tanggal Selesai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roombooking',
            name='date_start',
            field=models.DateField(default=datetime.date(2026, 2, 27), verbose_name='Tanggal Mulai'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomblockschedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], help_text='Isi jika blokir berulang tiap minggu pada hari ini.', null=True),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='participants',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah Peserta'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='purpose',
            field=models.TextField(verbose_name='Keperluan'),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Disetujui'), ('declined', 'Ditolak'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['date_start', 'room'], name='rooms_roomb_date_st_16aed6_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['date_end', 'room'], name='rooms_roomb_date_en_feaa56_idx'),
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='start_time',
        ),
    ]
