# Generated by Django 6.0.1 on 2026-02-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_roomblockschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('lab', 'Laboratorium'), ('class', 'Kelas / Ruang Teori'), ('office', 'Ruang Kantor'), ('other', 'Lainnya')], default='lab', max_length=20),
        ),
    ]
