# Generated by Django 6.0.1 on 2026-02-20 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='location',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='fail_reason',
            field=models.CharField(blank=True, choices=[('wrong_password', 'Password salah'), ('not_found', 'Akun tidak ditemukan'), ('not_verified', 'Akun belum diverifikasi'), ('inactive', 'Akun dinonaktifkan')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='angkatan',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Angkatan'),
        ),
        migrations.AddField(
            model_name='user',
            name='ktm_photo',
            field=models.ImageField(blank=True, null=True, upload_to='ktm/', verbose_name='Foto KTM/KTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='prodi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Program Studi'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('umkt', 'UMKT'), ('non_umkt', 'Non-UMKT / Umum')], default='umkt', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_users', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi oleh'),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='device_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
