# Generated by Django 6.0.1 on 2026-02-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_loginhistory_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginhistory',
            options={'ordering': ['-login_at'], 'verbose_name': 'Login History', 'verbose_name_plural': 'Login Histories'},
        ),
        migrations.RenameField(
            model_name='loginhistory',
            old_name='timestamp',
            new_name='login_at',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
