# Generated by Django 6.0.1 on 2026-03-02 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_loginhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_users', to=settings.AUTH_USER_MODEL, verbose_name='Ditolak oleh'),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Alasan Penolakan'),
        ),
    ]
