# Generated by Django 6.0.1 on 2026-03-03 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0002_alter_lecturer_focus_alter_researchtitle_focus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Instansi')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('field', models.CharField(help_text='Psikologi Klinis, Industri, dll', max_length=100, verbose_name='Bidang Magang')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='Kontak Person')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mitra Magang',
                'verbose_name_plural': 'Mitra Magang',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_name', models.CharField(blank=True, max_length=200, verbose_name='Nama Instansi')),
                ('partner_address', models.TextField(blank=True, verbose_name='Alamat Instansi')),
                ('partner_field', models.CharField(blank=True, max_length=100, verbose_name='Bidang Magang')),
                ('supervisor_name', models.CharField(max_length=150, verbose_name='Supervisor Lapangan')),
                ('supervisor_phone', models.CharField(max_length=20, verbose_name='No. HP Supervisor')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('total_days', models.PositiveIntegerField(default=0, verbose_name='Total Hari Magang')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('ongoing', 'Berjalan'), ('completed', 'Selesai'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('intro_letter', models.FileField(blank=True, null=True, upload_to='internship/docs/', verbose_name='Surat Pengantar')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='internship/reports/', verbose_name='Laporan Akhir')),
                ('assessment', models.FileField(blank=True, null=True, upload_to='internship/assessments/', verbose_name='Penilaian Supervisor')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_internships', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internships', to='research.lecturer', verbose_name='Dosen Pembimbing')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internship.internshippartner', verbose_name='Mitra Magang')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_requests', to=settings.AUTH_USER_MODEL, verbose_name='Mahasiswa')),
            ],
            options={
                'verbose_name': 'Pendaftaran Magang',
                'verbose_name_plural': 'Pendaftaran Magang',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Tanggal Kegiatan')),
                ('topic', models.CharField(max_length=200, verbose_name='Kegiatan')),
                ('notes', models.TextField(verbose_name='Deskripsi')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='internship/logs/', verbose_name='Lampiran')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='internship.internshiprequest')),
            ],
            options={
                'verbose_name': 'Log Magang',
                'verbose_name_plural': 'Log Magang',
                'ordering': ['-date'],
            },
        ),
    ]
