# Generated by Django 6.0.1 on 2026-06-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippartner',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='0 = tidak dibatasi', verbose_name='Kuota Tersedia'),
        ),
        migrations.AddField(
            model_name='internshippartner',
            name='quota_per_batch',
            field=models.PositiveIntegerField(default=0, help_text='0 = tidak ada pembatasan per gelombang', verbose_name='Kuota per Gelombang'),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='field',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
