# Generated by Django 6.0.1 on 2026-06-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_internshippartner_quota_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshippartner',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='internshippartner',
            name='quota_per_batch',
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='address',
            field=models.TextField(verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, verbose_name='Kontak Person'),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='field',
            field=models.CharField(max_length=100, verbose_name='Bidang Magang'),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nama Instansi'),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='0 = tanpa batas'),
        ),
    ]
