# Generated by Django 6.0.1 on 2026-06-05 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_alter_internshippartner_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshippartner',
            options={'ordering': ['name'], 'verbose_name': 'Mitra Magang', 'verbose_name_plural': 'Mitra Magang'},
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='field',
            field=models.CharField(help_text='Psikologi Klinis, Industri, dll', max_length=100, verbose_name='Bidang Magang'),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='quota',
            field=models.PositiveIntegerField(default=0, help_text='0 = tidak dibatasi', verbose_name='Kuota'),
        ),
    ]
