# Generated by Django 6.0.1 on 2026-06-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_alter_internshippartner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshippartner',
            name='keterangan',
            field=models.TextField(blank=True, help_text='Contoh: magang berbayar/tidak berbayar, syarat khusus, jam kerja, dll', verbose_name='Keterangan'),
        ),
    ]
