# Generated by Django 6.0.1 on 2026-06-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_internshippartner_keterangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshippartner',
            name='address',
            field=models.TextField(blank=True, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='field',
            field=models.CharField(blank=True, help_text='Psikologi Klinis, Industri, dll', max_length=100, verbose_name='Bidang Magang'),
        ),
        migrations.AlterField(
            model_name='internshippartner',
            name='keterangan',
            field=models.TextField(blank=True, help_text='Contoh: Magang berbayar/tidak berbayar, jam kerja, syarat khusus, dll', verbose_name='Keterangan'),
        ),
    ]
