# Generated by Django 6.0.1 on 2026-06-10 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_alter_internshippartner_address_and_more'),
        ('research', '0002_alter_lecturer_focus_alter_researchtitle_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshiprequest',
            name='lecturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internships', to='research.lecturer', verbose_name='Dosen Pembimbing'),
        ),
    ]
