# Generated by Django 6.0.1 on 2026-01-18 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('field', models.CharField(choices=[('klinis', 'Psikologi Klinis'), ('perkembangan', 'Psikologi Perkembangan'), ('sosial', 'Psikologi Sosial'), ('industri', 'Psikologi Industri & Organisasi'), ('pendidikan', 'Psikologi Pendidikan')], max_length=20)),
                ('description', models.TextField()),
                ('quota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('supervisor', models.ForeignKey(limit_choices_to={'role': 'dosen'}, on_delete=django.db.models.deletion.PROTECT, related_name='research_variables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Variable',
                'verbose_name_plural': 'Research Variables',
                'ordering': ['field', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VariableRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.FileField(upload_to='research/proposals/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_variable_requests', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_requests', to=settings.AUTH_USER_MODEL)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='research.researchvariable')),
            ],
            options={
                'verbose_name': 'Variable Request',
                'verbose_name_plural': 'Variable Requests',
                'ordering': ['-created_at'],
                'unique_together': {('variable', 'student')},
            },
        ),
        migrations.CreateModel(
            name='GuidanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='research/guidance/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_sessions', to='research.variablerequest')),
            ],
            options={
                'verbose_name': 'Guidance Session',
                'verbose_name_plural': 'Guidance Sessions',
                'ordering': ['-date'],
            },
        ),
    ]
