# Generated by Django 6.0.1 on 2026-02-23 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nama Dosen')),
                ('nip', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP')),
                ('focus', models.CharField(choices=[('klinis', 'Psikologi Klinis'), ('perkembangan', 'Psikologi Perkembangan'), ('sosial', 'Psikologi Sosial'), ('industri', 'Psikologi Industri & Organisasi'), ('pendidikan', 'Psikologi Pendidikan'), ('umum', 'Umum')], max_length=20, verbose_name='Bidang Fokus')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lecturers/')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Deskripsi Singkat')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dosen',
                'verbose_name_plural': 'Dosen',
                'ordering': ['focus', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('payung', 'Dalam Judul Payung'), ('individu', 'Individu (tanpa judul payung)')], default='payung', max_length=10, verbose_name='Tipe Request')),
                ('thesis_title', models.CharField(max_length=300, verbose_name='Judul Skripsi')),
                ('proposal', models.FileField(blank=True, null=True, upload_to='research/proposals/', verbose_name='File Proposal')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('completed', 'Selesai')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Catatan Admin')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_research_requests', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_requests', to='research.lecturer', verbose_name='Dosen Pembimbing')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_requests', to=settings.AUTH_USER_MODEL, verbose_name='Mahasiswa')),
            ],
            options={
                'verbose_name': 'Request Penelitian',
                'verbose_name_plural': 'Request Penelitian',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Tanggal Bimbingan')),
                ('topic', models.CharField(max_length=200, verbose_name='Topik')),
                ('notes', models.TextField(verbose_name='Catatan')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='research/guidance/', verbose_name='Lampiran')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_sessions', to='research.researchrequest')),
            ],
            options={
                'verbose_name': 'Sesi Bimbingan',
                'verbose_name_plural': 'Sesi Bimbingan',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Judul Payung')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Deskripsi')),
                ('focus', models.CharField(choices=[('klinis', 'Psikologi Klinis'), ('perkembangan', 'Psikologi Perkembangan'), ('sosial', 'Psikologi Sosial'), ('industri', 'Psikologi Industri & Organisasi'), ('pendidikan', 'Psikologi Pendidikan'), ('umum', 'Umum')], max_length=20, verbose_name='Bidang')),
                ('quota', models.PositiveIntegerField(default=5, verbose_name='Kuota Mahasiswa')),
                ('is_active', models.BooleanField(default=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_titles', to='research.lecturer', verbose_name='Dosen Pembimbing')),
            ],
            options={
                'verbose_name': 'Judul Payung',
                'verbose_name_plural': 'Judul Payung',
                'ordering': ['lecturer', 'title'],
            },
        ),
        migrations.AddField(
            model_name='researchrequest',
            name='research_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='research.researchtitle', verbose_name='Judul Payung (opsional)'),
        ),
    ]
