# Generated by Django 6.0.1 on 2026-02-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='focus',
            field=models.CharField(choices=[('klinis', 'Psikologi Klinis'), ('perkembangan', 'Psikologi Perkembangan'), ('sosial', 'Psikologi Sosial'), ('industri', 'Psikologi Industri & Organisasi'), ('agama', 'Psikologi Islam'), ('pendidikan', 'Psikologi Pendidikan'), ('umum', 'Umum')], max_length=20, verbose_name='Bidang Fokus'),
        ),
        migrations.AlterField(
            model_name='researchtitle',
            name='focus',
            field=models.CharField(choices=[('klinis', 'Psikologi Klinis'), ('perkembangan', 'Psikologi Perkembangan'), ('sosial', 'Psikologi Sosial'), ('industri', 'Psikologi Industri & Organisasi'), ('agama', 'Psikologi Islam'), ('pendidikan', 'Psikologi Pendidikan'), ('umum', 'Umum')], max_length=20, verbose_name='Bidang'),
        ),
    ]
