# Generated by Django 6.0.1 on 2026-01-18 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Practicum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('inteligensi', 'Praktikum Inteligensi'), ('inventory', 'Praktikum Inventory'), ('wawancara', 'Praktikum Wawancara'), ('konseling', 'Praktikum Konseling')], max_length=20)),
                ('session_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practicum_sessions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Practicum',
                'verbose_name_plural': 'Practicums',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='PracticumRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('waitlist', 'Waitlist'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('certificate_issued', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='practicum/certificates/')),
                ('practicum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='practicum.practicum')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practicum_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practicum Registration',
                'verbose_name_plural': 'Practicum Registrations',
                'ordering': ['-created_at'],
                'unique_together': {('practicum', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='practicum.practicumregistration')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date'],
                'unique_together': {('registration', 'date')},
            },
        ),
    ]
