# Generated by Django 6.0.1 on 2026-03-13 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0001_initial'),
        ('research', '0002_alter_lecturer_focus_alter_researchtitle_focus'),
        ('rooms', '0003_room_room_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practicum',
            unique_together={('lecturer', 'room', 'date', 'start_time')},
        ),
    ]
