# Generated by Django 6.0.1 on 2026-03-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0003_alter_practicum_unique_together'),
        ('research', '0002_alter_lecturer_focus_alter_researchtitle_focus'),
        ('rooms', '0003_room_room_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practicum',
            unique_together={('lecturer', 'date', 'start_time'), ('room', 'date', 'start_time')},
        ),
    ]
