# Generated by Django 6.0.1 on 2026-03-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practicum', '0004_alter_practicum_unique_together'),
        ('rooms', '0003_room_room_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practicum',
            unique_together={('room', 'date', 'start_time')},
        ),
    ]
