# Generated by Django 6.0.1 on 2026-02-22 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KonselingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_preferensi', models.DateField(help_text='Tanggal yang diinginkan klien')),
                ('waktu_preferensi', models.TimeField(help_text='Jam yang diinginkan klien')),
                ('tanggal_aktual', models.DateField(blank=True, help_text='Jadwal final oleh admin', null=True)),
                ('waktu_aktual', models.TimeField(blank=True, null=True)),
                ('tujuan', models.CharField(choices=[('akademik', 'Masalah Akademik'), ('karir', 'Perencanaan Karir'), ('pribadi', 'Masalah Pribadi'), ('sosial', 'Masalah Sosial/Relasi'), ('keluarga', 'Masalah Keluarga'), ('kecemasan', 'Kecemasan / Stres'), ('lainnya', 'Lainnya')], max_length=20)),
                ('keluhan', models.TextField(help_text='Deskripsi keluhan / tujuan konseling')),
                ('catatan_admin', models.TextField(blank=True, help_text='Catatan dari admin/psikolog')),
                ('ruangan', models.CharField(blank=True, max_length=100)),
                ('psikolog', models.CharField(blank=True, max_length=150)),
                ('tarif', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sudah_bayar', models.BooleanField(default=False)),
                ('bukti_bayar', models.ImageField(blank=True, null=True, upload_to='konseling/bukti/')),
                ('consent_disetujui', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('rejected', 'Ditolak'), ('done', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20)),
                ('alasan_tolak', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konseling_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesi Konseling',
                'verbose_name_plural': 'Sesi Konseling',
                'ordering': ['-created_at'],
            },
        ),
    ]
