# Generated by Django 6.0.1 on 2026-02-27 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konseling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='konselingsession',
            name='bayar_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='konselingsession',
            name='bayar_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='konselingsession',
            name='catatan_rujukan',
            field=models.TextField(blank=True, verbose_name='Catatan rujukan'),
        ),
        migrations.AddField(
            model_name='konselingsession',
            name='dirujuk',
            field=models.BooleanField(default=False, verbose_name='Dirujuk ke layanan lain'),
        ),
        migrations.AddField(
            model_name='konselingsession',
            name='laporan_pdf',
            field=models.FileField(blank=True, null=True, upload_to='konseling/laporan/', verbose_name='Laporan/Hasil PDF'),
        ),
        migrations.AddField(
            model_name='konselingsession',
            name='selesai_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
