# Generated by Django 6.0.1 on 2026-02-27 02:37

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(choices=[('lembar', 'Lembar'), ('set', 'Set'), ('buah', 'Buah')], default='lembar', max_length=20)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.PositiveIntegerField(default=0, help_text='Harga per unit dalam rupiah')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Test Tool',
                'verbose_name_plural': 'Test Tools',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='toolblockschedule',
            name='tool',
        ),
        migrations.AlterModelOptions(
            name='toolrental',
            options={'ordering': ['-date_start', '-created_at'], 'verbose_name': 'Tool Rental', 'verbose_name_plural': 'Tool Rentals'},
        ),
        migrations.RenameField(
            model_name='toolrental',
            old_name='payment_status',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='toolrental',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='toolrental',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='toolrental',
            name='instansi',
        ),
        migrations.RemoveField(
            model_name='toolrental',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='toolrental',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='toolrental',
            name='with_answer_sheet',
        ),
        migrations.RemoveField(
            model_name='toolrental',
            name='with_book',
        ),
        migrations.RemoveField(
            model_name='toolrental',
            name='with_norms',
        ),
        migrations.AddField(
            model_name='toolrental',
            name='components',
            field=models.JSONField(blank=True, default=list, help_text='Komponen yang dipinjam: ["buku_tes", "lj", "norma"]'),
        ),
        migrations.AddField(
            model_name='toolrental',
            name='date_end',
            field=models.DateField(default=datetime.date(2026, 2, 27), verbose_name='Tanggal Kembali'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolrental',
            name='date_start',
            field=models.DateField(default=datetime.date(2026, 2, 27), verbose_name='Tanggal Mulai Pinjam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolrental',
            name='institution',
            field=models.CharField(choices=[('umkt', 'UMKT'), ('non_umkt', 'Non-UMKT')], default='umkt', max_length=20),
        ),
        migrations.AddField(
            model_name='toolrental',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='tool_rentals/payments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='toolrental',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='toolrental',
            name='activity_letter',
            field=models.FileField(blank=True, help_text='Surat kegiatan (PDF/JPG/PNG)', null=True, upload_to='tool_rentals/letters/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='toolrental',
            name='agreement_file',
            field=models.FileField(blank=True, help_text='Surat perjanjian yang sudah ditandatangani', null=True, upload_to='tool_rentals/agreements/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='toolrental',
            name='payment_time',
            field=models.CharField(choices=[('before', 'Sebelum Peminjaman'), ('after', 'Sesudah Peminjaman')], default='before', max_length=10),
        ),
        migrations.AlterField(
            model_name='toolrental',
            name='purpose',
            field=models.CharField(choices=[('seleksi_dosen', 'Seleksi Dosen UMKT'), ('seleksi_karyawan', 'Seleksi Karyawan Non-UMKT'), ('pelatihan', 'Pelatihan Alat Tes Internal'), ('penelitian', 'Penelitian Individu/Kelompok'), ('lainnya', 'Kegiatan Lainnya')], max_length=30),
        ),
        migrations.AlterField(
            model_name='toolrental',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Disetujui'), ('borrowed', 'Dipinjam'), ('returned', 'Dikembalikan'), ('declined', 'Ditolak'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='toolrental',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='tools.testtool'),
        ),
        migrations.AddIndex(
            model_name='toolrental',
            index=models.Index(fields=['date_start', 'tool'], name='tools_toolr_date_st_3a1fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='toolrental',
            index=models.Index(fields=['status'], name='tools_toolr_status_68e959_idx'),
        ),
        migrations.AddIndex(
            model_name='toolrental',
            index=models.Index(fields=['user'], name='tools_toolr_user_id_615c8d_idx'),
        ),
        migrations.DeleteModel(
            name='ToolBlockSchedule',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
