# Generated by Django 6.0.1 on 2026-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_testtool_remove_toolblockschedule_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtool',
            name='kategori',
            field=models.CharField(choices=[('inteligensi', 'Inteligensi'), ('kepribadian', 'Kepribadian'), ('minat', 'Minat & Bakat'), ('klinis', 'Klinis'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20),
        ),
        migrations.AlterField(
            model_name='testtool',
            name='price_per_unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
