# Generated by Django 6.0.1 on 2026-03-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_testtool_kategori_alter_testtool_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolrental',
            name='fine_amount',
            field=models.PositiveIntegerField(default=0, help_text='Denda keterlambatan dalam Rupiah'),
        ),
        migrations.AddField(
            model_name='toolrental',
            name='transaction_type',
            field=models.CharField(choices=[('pinjam', 'Peminjaman'), ('sewa', 'Penyewaan'), ('beli', 'Pembelian')], default='pinjam', max_length=10),
        ),
    ]
