# Generated by Django 6.0.1 on 2026-03-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_toolrental_fine_amount_toolrental_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtool',
            name='transaction_type',
            field=models.CharField(choices=[('pinjam', 'Peminjaman'), ('sewa', 'Penyewaan'), ('beli', 'Pembelian')], default='pinjam', max_length=10),
        ),
    ]
