# Generated by Django 6.0.1 on 2026-04-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_testtool_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolrental',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Persetujuan'), ('approved', 'Disetujui'), ('payment_pending', 'Menunggu Verifikasi Bayar'), ('borrowed', 'Sedang Dipinjam'), ('overdue', 'Terlambat'), ('returning', 'Diajukan Kembali'), ('returned', 'Selesai'), ('declined', 'Ditolak'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20),
        ),
    ]
